name: RPGEssentials
main: me.G4meM0ment.RPGEssentials.RPGEssentials
version: 0.00.001
Author: [G4meM0ment, Eatingyou]
depend: [Vault]
softdepend: [Spout, Jail, WorldGuard, Factions, MCore]
commands:
    ge:
        aliases: [ge]
        description: Command for the main plugin
        usage: /ge [reload]
    rpgitem:
        aliases: [rpgitem]
        description: Main command for RPGItem
        usage: /rpgitem help
    upp:
        aliases: [upp]
        description: Main command for UnnamedPortalPlugin
        usage: /upp help
    rentables:
        aliases: [rentables]
        description: Main command for Rentables
        usage: /rentables help